### ISSUE TITLE
Language Pair Not supported

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#289]
Hey Team

We are experiencing a completely new issue when submitting an order.  It only occurs when targeting one language (Japan), other languages submit find.  Or if Japanese is the source and anything else is the target, we get another error. We have not changed any config on our side.  Here is the response and thanks!  

![MicrosoftTeams-image](https://user-images.githubusercontent.com/48130527/149393270-87f1bfd0-6a3e-4475-b2eb-d9f62c705559.png)

**Comment by sidedwards** [comment]
@masonry47, which version of the plugin are you currently using?

**Comment by masonry47** [comment]
v2.1.1. Thanks!

**Comment by sidedwards** [comment]
@masonry47, thanks for reporting; this issue was resolved in [`v2.1.2`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.1.2).

**Comment by sidedwards** [comment]
@masonry47, could you please provide some additional details? We were able to successfully place the following test orders:

1. `en-US` to `ja-JP`
2. `ja-JP` to `en-US`

**Comment by sidedwards** [comment]
@masonry47, please try again; these specific ISO mappings are now enabled in the My Acclaro API.

**Comment by masonry47** [comment]
Seems to have had a positive effect but still getting fr to pt-BR issue.

**Comment by masonry47** [comment]
That got it.  Thanks!
